### PR TITLE
Charzy portfolio/work section

### PR DESCRIPTION
**Pull request by Charzy-1**
This is the mobile version of my portfolio project.
I added a work section that shows cards displaying the jobs i have done
About me info was also stated 
buttons were added

### CODE REVIEW

**Review by basitali111 — CHANGES_REQUESTED** [review]
# Required Changes ♻️

Hi @Charzy-1 ,

# Code review blocked.
- You cannot directly go to the next Assignment without doing the first Assignment because it affects your overall project and these assignments are designed in sequence order if you skip one part and go for another then you get a lot of errors and run into major problems that are unable to solve so next time please avoid it thanks. 


# Highlights
✔️ Professional Readme
✔️ Correct Gitflow
✔️ Linter Check Pass
## Required 
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@basitali111] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Charzy-1** [comment]
I build the middle section of the mobile website. This sections of the mobile website includes:
"Works" section and the "About myself" section 

Kindly review. @basitali111

**Review by basitali111 — CHANGES_REQUESTED** [review]
# Required Changes ♻️

Hi @Charzy-1 ,

# Code review blocked.
- Could you resolve the conflicts in your code and check your linter's configuration? It does not show that all checks are passing.

Apex_1716428932454

# Highlights
✔️ Professional Readme
✔️ Correct Gitflow

## Required 
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@basitali111] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Charzy-1** [comment]
HI @basitali111 . I have resolved the conflicts on github flow. Kindly go ahead with the review. Thanks

**Review by basitali111 — CHANGES_REQUESTED** [review]
# Required Changes ♻️
Hi @Charzy-1 ,
Good job so far!
## You are almost finished. Please work on both the desktop and mobile versions.
## Desktop:
-  Please remember to leave some space between "My Recent Work" and the following line.
[
Apex_1716514058324
](URL)
## Original design is:
Apex_1716513001883

- During the hover on the card from the mouse, it will change into a 'See Project' button that is orange. Kindly work on that.
## On Mobile:
Apex_1716513139442
## On Desktop:
 
Apex_1716513021266

There are still some issues that need to be addressed before moving on to the next project, but you are almost there!

giphy_2


## Highlights
✔️ No Linters errors
✔️ Professional Readme
✔️ Correct Gitflow

## Required
 Check the comments under the review.
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@basitali111] in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**Comment by Charzy-1** [comment]
Hi @basitali111 i have corrected the version of my code to accomodate the hovering effect on my card and also the space between the items on my work section. Please check

**Review by basitali111 — CHANGES_REQUESTED** [review]
# Required Changes ♻️
Hi @Charzy-1 ,
Good job so far!
- Kindly review the video and implement the necessary changes for the upcoming review.

- [Click here to watch vedio](https://streamable.com/ypuwgj)

There are still some issues that need to be addressed before moving on to the next project, but you are almost there!

giphy_2


## Highlights
✔️ No Linters errors
✔️ Professional Readme
✔️ Correct Gitflow

## Required
 Check the comments under the review.
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@basitali111] in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**Comment by Charzy-1** [comment]
Hi @basitali111 i have modified the code to accomodate the corrections made on the previous review on my hovering effect and removing unecessary spaces.

**Review by basitali111 — CHANGES_REQUESTED** [review]
# Required Changes ♻️
Hi @Charzy-1 ,
Good job so far!
- Kindly review the video and implement the necessary changes for the upcoming review.

- [Click here to watch vedio](https://streamable.com/z2q41b)

There are still some issues that need to be addressed before moving on to the next project, but you are almost there!

giphy_2


## Highlights
✔️ No Linters errors
✔️ Professional Readme
✔️ Correct Gitflow

## Required
 Check the comments under the review.
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@basitali111] in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**Comment by Charzy-1** [comment]
Hi @basitali111 can we meet now? I don't understand what you said on the video here

**Comment by Charzy-1** [comment]
Please can we meet? I don't understand the correction you are making. on
which screen size because the ho
ver correction you made again are all working on my part

**Comment by basitali111** [comment]
Hi @Charzy-1/My-Portfolio-Website,

Please join this meeting.

https://microverse.zoom.us/j/94395886649?pwd=NTVVM01nTmZOSDNDNWovdVgzZWhhdz09

**Comment by Charzy-1** [comment]
Hi @basitali111 i have corrected my grid to make it customized. Please check

**Review by basitali111 — CHANGES_REQUESTED** [review]
# Required Changes ♻️
Hi @Charzy-1 ,
Good job so far!
- **It's good that you use your styling pattern to design the grid, but please don't completely ignore the Figma file. The items that must be included in the grid are skill buttons that show which skills are used in any project.**
Apex_1716610979008
- **Kindly make the length of the card according to the Figma design so it looks attractive in my opinion.**
Apex_1716611031967


Some issues still need to be addressed before moving on to the next project, but you are almost there!

giphy_2


## Highlights
✔️ No Linters errors
✔️ Professional Readme
✔️ Correct Gitflow

## Required
 Check the comments under the review.
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me [@basitali111] in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**Comment by Charzy-1** [comment]
Hi @basitali111 I modified my project box by making it dynamic for so i can update it in the future. Please check.

**Review by basitali111 — CHANGES_REQUESTED** [review]
Hi @Charzy-1

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉
- [optional] - "Next time, please try to arrange your card text more precisely. Match your design with the text arrangement, such as the font style, to make it more attractive. Kindly work on that and deeply analyze the Figma design."

giphy

Highlights
No linter errors ✅
Good Pr title and description 💪🏿
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Kindly make use of the provided README.md template provided in your dashboard otherwise the next project will be marked as invalid
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @Pamphilemkp

_As described in the Code reviews limits policy you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion by contacting us.

**Pull request merged**
